// Code generated by splitting main.go. Part of package main.
package storage

import (
	"bytes"
	"github.com/google/uuid"
	natomic "github.com/natefinch/atomic"
	"os"
	"path/filepath"
	"sync"
)

// newID generates a UUIDv4 ID for externally-stored blobs. Duplicated
// (rather than imported) from the root package's misc_utils.go to keep
// this package dependency-free.
func newID() string {
	return uuid.New().String()
}

type ExternalStorage interface {
	Save(data []byte) (string, error)
	Load(id string) ([]byte, error)
	Delete(id string) error
	Exists(id string) bool
}

type FileSystemStorage struct {
	basePath string
	mu       sync.RWMutex
}

func NewFileSystemStorage(basePath string) (*FileSystemStorage, error) {
	if err := os.MkdirAll(basePath, 0750); err != nil {
		return nil, err
	}
	return &FileSystemStorage{basePath: basePath}, nil
}

func (fs *FileSystemStorage) Save(data []byte) (string, error) {
	id := newID()
	path := filepath.Join(fs.basePath, id[:2], id)
	if err := os.MkdirAll(filepath.Dir(path), 0750); err != nil {
		return "", err
	}
	// natefinch/atomic writes to a temp file in the same directory and
	// renames it into place, so a crash or concurrent Load() mid-write
	// can never observe a partially-written blob at `path` -- os.WriteFile
	// offers no such guarantee (a truncate + partial write is visible to
	// readers the instant it starts).
	if err := natomic.WriteFile(path, bytes.NewReader(data)); err != nil {
		return "", err
	}
	return id, nil
}

func (fs *FileSystemStorage) Load(id string) ([]byte, error) {
	path := filepath.Join(fs.basePath, id[:2], id)
	return os.ReadFile(path)
}

func (fs *FileSystemStorage) Delete(id string) error {
	path := filepath.Join(fs.basePath, id[:2], id)
	return os.Remove(path)
}

func (fs *FileSystemStorage) Exists(id string) bool {
	path := filepath.Join(fs.basePath, id[:2], id)
	_, err := os.Stat(path)
	return err == nil
}
