// Code generated by splitting main.go. Part of package main.
package caimandb

import (
	"fmt"
	"strconv"
	"strings"
)

// stripQuotes quita un par de comillas simples o dobles que envuelvan
// por completo el token (tal como los deja parse.Tokenize, que conserva
// las comillas dentro del token). Si el token no está entre comillas, se
// devuelve tal cual -- así "MiPassword123" y MiPassword123 funcionan
// igual.
func stripQuotes(s string) string {
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			return s[1 : len(s)-1]
		}
	}
	return s
}

func handleCreate(eng *Engine, sess *Session, tokens []string) string {
	subCmd := strings.ToUpper(tokens[1])
	switch subCmd {
	case "DB":
		if len(tokens) < 3 {
			return "ERROR: CREATE DB requires database name"
		}
		db := tokens[2]
		if err := eng.CreateDB(db); err != nil {
			return "ERROR: " + err.Error()
		}
		return "Database created: " + db

	case "BLOCK":
		var db, block string
		if len(tokens) == 3 {
			block = tokens[2]
			db = sess.currentDB
			if db == "" {
				return "ERROR: No database in use. Use: CREATE BLOCK <db> <block> or USE <db> first"
			}
		} else if len(tokens) >= 4 {
			db = tokens[2]
			block = tokens[3]
		} else {
			return "ERROR: CREATE BLOCK requires block name"
		}
		if db == "" {
			return "ERROR: No database specified and no database in use"
		}
		if err := eng.CreateBlock(db, block); err != nil {
			return "ERROR: " + err.Error()
		}
		return "Block created: " + block + " in database: " + db

	case "USER":
		if len(tokens) < 3 {
			return "ERROR: CREATE USER requires a username"
		}
		return handleCreateUser(eng, tokens[2], tokens[3:])

	case "SERVER":
		if len(tokens) < 3 {
			return `ERROR: CREATE SERVER requires a server name -- syntax: CREATE SERVER <name> ADMIN [<username>] IDENTIFIED BY "<password>"`
		}
		return handleCreateServer(eng, tokens[2], tokens[3:])

	default:
		return "ERROR: unknown CREATE object: " + subCmd
	}
}

// handleCreateUser implementa la sintaxis completa de CREATE USER, tanto
// "en línea" como "en cascada" (el operador puede escribirla en varias
// líneas: ver el buffer de sentencias en app.go, que las junta en una
// sola antes de llegar aquí). Todas las cláusulas después del nombre de
// usuario son opcionales salvo IDENTIFIED BY, y pueden ir en cualquier
// orden:
//
//	CREATE USER <username> IDENTIFIED BY "<password>"
//	    [ROLE <ADMIN|SUBADMIN|DEVELOPER|USER>]
//	    [STATUS <ACTIVE|DISABLED>]
//	    [DEFAULT DATABASE <database>]
//	    [DEFAULT BLOCK <block>]
//	    [PASSWORD EXPIRE <NEVER|DAYS n>]
//	    [ACCOUNT LOCK <ON|OFF>]
//	    [COMMENT "<description>"]
//
// También se acepta la forma corta heredada: CREATE USER <user> <pass>
// [ROLE <role>].
func handleCreateUser(eng *Engine, username string, args []string) string {
	var password string
	havePassword := false
	opts := CreateUserOpts{}

	// Forma corta heredada: CREATE USER <user> <pass> [ROLE <role>]
	if len(args) > 0 && strings.ToUpper(args[0]) != "IDENTIFIED" {
		password = stripQuotes(args[0])
		havePassword = true
		args = args[1:]
		if len(args) >= 2 && strings.ToUpper(args[0]) == "ROLE" {
			opts.Role = args[1]
			args = args[2:]
		}
	}

	for i := 0; i < len(args); {
		tok := strings.ToUpper(args[i])
		switch tok {
		case "IDENTIFIED":
			if i+2 >= len(args) || strings.ToUpper(args[i+1]) != "BY" {
				return `ERROR: expected IDENTIFIED BY "<password>"`
			}
			password = stripQuotes(args[i+2])
			havePassword = true
			i += 3

		case "ROLE":
			if i+1 >= len(args) {
				return "ERROR: ROLE requires a value (ADMIN, SUBADMIN, DEVELOPER or USER)"
			}
			opts.Role = args[i+1]
			i += 2

		case "STATUS":
			if i+1 >= len(args) {
				return "ERROR: STATUS requires ACTIVE or DISABLED"
			}
			opts.Status = args[i+1]
			i += 2

		case "DEFAULT":
			if i+2 >= len(args) {
				return "ERROR: DEFAULT requires DATABASE <name> or BLOCK <name>"
			}
			switch strings.ToUpper(args[i+1]) {
			case "DATABASE":
				opts.DefaultDatabase = args[i+2]
			case "BLOCK":
				opts.DefaultBlock = args[i+2]
			default:
				return "ERROR: DEFAULT must be followed by DATABASE or BLOCK"
			}
			i += 3

		case "PASSWORD":
			if i+1 >= len(args) || strings.ToUpper(args[i+1]) != "EXPIRE" {
				return "ERROR: expected PASSWORD EXPIRE NEVER, or PASSWORD EXPIRE DAYS <n>"
			}
			if i+2 >= len(args) {
				return "ERROR: PASSWORD EXPIRE requires NEVER or DAYS <n>"
			}
			switch strings.ToUpper(args[i+2]) {
			case "NEVER":
				opts.PasswordExpireDays = 0
				i += 3
			case "DAYS":
				if i+3 >= len(args) {
					return "ERROR: PASSWORD EXPIRE DAYS requires a number of days"
				}
				n, err := strconv.Atoi(args[i+3])
				if err != nil || n < 0 {
					return "ERROR: invalid PASSWORD EXPIRE DAYS value: " + args[i+3]
				}
				opts.PasswordExpireDays = n
				i += 4
			default:
				return "ERROR: PASSWORD EXPIRE must be NEVER or DAYS <n>"
			}

		case "ACCOUNT":
			if i+2 >= len(args) || strings.ToUpper(args[i+1]) != "LOCK" {
				return "ERROR: expected ACCOUNT LOCK ON or ACCOUNT LOCK OFF"
			}
			switch strings.ToUpper(args[i+2]) {
			case "ON":
				opts.AccountLock = true
			case "OFF":
				opts.AccountLock = false
			default:
				return "ERROR: ACCOUNT LOCK must be ON or OFF"
			}
			i += 3

		case "COMMENT":
			if i+1 >= len(args) {
				return "ERROR: COMMENT requires a value"
			}
			opts.Comment = stripQuotes(args[i+1])
			i += 2

		default:
			return "ERROR: unexpected token in CREATE USER near '" + args[i] + "'"
		}
	}

	if !havePassword {
		return `ERROR: CREATE USER requires IDENTIFIED BY "<password>"`
	}
	if opts.Role == "" {
		opts.Role = RoleUser
	}

	if err := eng.CreateUserWithOpts(username, password, opts); err != nil {
		return "ERROR: " + err.Error()
	}
	role, _ := normalizeRole(opts.Role)
	return fmt.Sprintf("User created: %s (role: %s)", username, role)
}

// handleCreateServer implementa:
//
//	CREATE SERVER <name> ADMIN [<username>] IDENTIFIED BY "<password>"
//
// Crea un servidor nuevo (su propio directorio de datos, aislado de los
// demás, y su propio usuario ADMIN) que atiende por el mismo puerto que
// el resto -- lo único que lo distingue son las credenciales de su
// admin. Si <username> se omite, se usa "admin".
func handleCreateServer(eng *Engine, name string, args []string) string {
	if len(args) < 1 || strings.ToUpper(args[0]) != "ADMIN" {
		return `ERROR: syntax: CREATE SERVER <name> ADMIN [<username>] IDENTIFIED BY "<password>"`
	}
	rest := args[1:]

	username := ""
	if len(rest) > 0 && strings.ToUpper(rest[0]) != "IDENTIFIED" {
		username = rest[0]
		rest = rest[1:]
	}

	if len(rest) < 3 || strings.ToUpper(rest[0]) != "IDENTIFIED" || strings.ToUpper(rest[1]) != "BY" {
		return `ERROR: syntax: CREATE SERVER <name> ADMIN [<username>] IDENTIFIED BY "<password>"`
	}
	password := stripQuotes(rest[2])

	if eng.serverMgr == nil {
		return "ERROR: multi-server support is not available on this instance"
	}
	if err := eng.serverMgr.CreateServer(name, username, password); err != nil {
		return "ERROR: " + err.Error()
	}
	if username == "" {
		username = "admin"
	}
	return fmt.Sprintf("Server created: %s (admin: %s) -- same port, reachable with its own credentials", name, username)
}

func handleShow(eng *Engine, sess *Session, tokens []string) string {
	subCmd := strings.ToUpper(tokens[1])
	switch subCmd {
	case "DBS":
		return handleShowDBs(eng, tokens[2:])

	case "BLOCKS":
		return handleShowBlocks(eng, sess, tokens[2:])

	case "USERS":
		users, err := eng.ShowUsers()
		if err != nil {
			return "ERROR: " + err.Error()
		}
		if len(users) == 0 {
			return "No users found"
		}
		var sb strings.Builder
		sb.WriteString("Users:\n")
		for _, u := range users {
			sb.WriteString(fmt.Sprintf("  %s (role: %s, status: %v, locked: %v)\n",
				u["username"], u["role"], u["status"], u["locked"]))
		}
		return sb.String()

	case "ROLES":
		roles := eng.ShowRoles()
		var sb strings.Builder
		sb.WriteString("Roles:\n")
		for _, r := range roles {
			sb.WriteString(fmt.Sprintf("  %-10s %s\n", r["role"], r["description"]))
		}
		return sb.String()

	case "SERVERS":
		if eng.serverMgr == nil {
			return "No additional servers (multi-server not available on this instance)"
		}
		names := eng.serverMgr.ListServers()
		if len(names) == 0 {
			return "No additional servers"
		}
		var sb strings.Builder
		sb.WriteString("Servers:\n")
		for _, n := range names {
			sb.WriteString("  " + n + "\n")
		}
		return sb.String()

	case "CACHE":
		stats := eng.l1Cache.Stats()
		return "L1 Cache:\n" + jsonOut(stats)

	case "INDEXES":
		var db string
		if len(tokens) > 2 {
			db = tokens[2]
		} else {
			db = sess.currentDB
		}
		if db == "" {
			return "ERROR: No database specified and no database in use"
		}
		cfg, ok := eng.intelEngine.GetConfig(db)
		if !ok {
			return "ERROR: Database not found: " + db
		}
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("Indexes in %s:\n", db))
		if len(cfg.Indexes) == 0 {
			sb.WriteString("  No indexes defined\n")
		} else {
			for _, idx := range cfg.Indexes {
				sb.WriteString(fmt.Sprintf("  %s\n", idx))
			}
		}
		return sb.String()

	case "SHARDS":
		sm := eng.shardMgr
		sm.mu.RLock()
		defer sm.mu.RUnlock()
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("Shard Distribution:\n"))
		sb.WriteString(fmt.Sprintf("%-12s %-10s %-12s %-10s %-20s\n", "SHARD", "DOCS", "SIZE", "PRIMARY", "NODES"))
		sb.WriteString(strings.Repeat("-", 70) + "\n")
		for id, shard := range sm.shards {
			primaryShort := shard.Primary
			if len(primaryShort) > 10 {
				primaryShort = primaryShort[:8] + "..."
			}
			sb.WriteString(fmt.Sprintf("%-12s %-10d %-12s %-10s %-20v\n",
				id, shard.DocCount, fmtBytes(shard.SizeBytes), primaryShort, shard.Nodes))
		}
		sb.WriteString(strings.Repeat("-", 70) + "\n")
		sb.WriteString(fmt.Sprintf("Total shards: %d, Total docs: %d\n", sm.shardCount, sm.totalDocs()))
		return sb.String()

	case "AUTORELATIONS", "AUTO-RELATIONS":
		return handleShowAutoRelations(eng, sess, tokens[2:])

	case "VIEWS":
		viewsMu.RLock()
		defer viewsMu.RUnlock()
		if len(views) == 0 {
			return "No views defined"
		}
		var sb strings.Builder
		sb.WriteString("Views:\n")
		for name, v := range views {
			sb.WriteString(fmt.Sprintf("  %s (db: %s, block: %s)\n", name, v.DB, v.Block))
		}
		return sb.String()

	default:
		return "ERROR: unknown SHOW object: " + subCmd
	}
}
