// Code generated by splitting main.go. Part of package main.
package caimandb

import (
	"time"
)

type Config struct {
	DataRoot      string `json:"data_root"`
	CacheMB       int    `json:"cache_mb"`
	L2CacheMB     int    `json:"l2_cache_mb"`
	Workers       int    `json:"workers"`
	LogLevel      string `json:"log_level"`
	MetricsPort   int    `json:"metrics_port"`
	RaftPort      int    `json:"raft_port"`
	RaftBind      string `json:"raft_bind"`
	QueryPort     int    `json:"query_port"`
	AdminPort     int    `json:"admin_port"`
	QueryUser     string `json:"query_user"`
	QueryPassword string `json:"query_password"`
	// UIDir is the filesystem path to the pure HTML/CSS/JS admin console
	// (the ui/ folder). The query server serves it directly at "/" on
	// QueryPort, alongside /query, /status, /health and /watch, so the
	// whole thing works same-origin with no separate static server and
	// no file:// CORS restrictions. Empty/missing directory just means
	// "/" 404s; the JSON API endpoints are unaffected.
	UIDir        string `json:"ui_dir"`
	ShardCount   int    `json:"shard_count"`
	ReplicaCount int    `json:"replica_count"`
	WALSegments  int    `json:"wal_segments"`
	AutoCluster  bool   `json:"auto_cluster"`

	// WALSyncPolicy controls fsync/group-commit behavior: "always" (fsync
	// every batch, safest/slowest), "interval" (group-commit: fsync on the
	// periodic ticker only — default, best throughput/durability balance
	// for sustained real-time write load), or "off" (never explicit fsync).
	WALSyncPolicy string `json:"wal_sync_policy"`

	FastStartup       bool `json:"fast_startup"`
	LazyIndexLoading  bool `json:"lazy_index_loading"`
	PreloadCache      bool `json:"preload_cache"`
	CompressLargeDocs bool `json:"compress_large_docs"`
	SkipLargeIndexes  bool `json:"skip_large_indexes"`
	UseStreamingWAL   bool `json:"use_streaming_wal"`

	MaxShardsPerNode  int   `json:"max_shards_per_node"`
	MaxClusterNodes   int   `json:"max_cluster_nodes"`
	AutoScaleInterval int   `json:"auto_scale_interval"`
	PredictionWindow  int   `json:"prediction_window"`
	MinShardDocs      int64 `json:"min_shard_docs"`
	MaxShardDocs      int64 `json:"max_shard_docs"`
	ScaleUpCooldown   int   `json:"scale_up_cooldown"`
	ScaleDownCooldown int   `json:"scale_down_cooldown"`
	AutoMergeEnabled  bool  `json:"auto_merge_enabled"`
	AutoSplitEnabled  bool  `json:"auto_split_enabled"`
	PredictiveScaling bool  `json:"predictive_scaling"`
	AggressiveScaling bool  `json:"aggressive_scaling"`
	MaxReplicas       int   `json:"max_replicas"`
	MinReplicas       int   `json:"min_replicas"`

	MaxDocumentSize    int64 `json:"max_document_size"`
	CompressThreshold  int64 `json:"compress_threshold"`
	IndexSkipThreshold int64 `json:"index_skip_threshold"`
	LargeDocThreshold  int64 `json:"large_doc_threshold"`

	MaxConcurrentQueries int           `json:"max_concurrent_queries"`
	QueryTimeout         time.Duration `json:"query_timeout"`
	TransactionTimeout   time.Duration `json:"transaction_timeout"`
	MaxQueryDepth        int           `json:"max_query_depth"`
	MaxBatchSize         int           `json:"max_batch_size"`
	RateLimit            int           `json:"rate_limit"`

	JWTSecret        string        `json:"jwt_secret"`
	TokenExpiry      time.Duration `json:"token_expiry"`
	MaxLoginAttempts int           `json:"max_login_attempts"`
	LockoutDuration  time.Duration `json:"lockout_duration"`
	TLSEnabled       bool          `json:"tls_enabled"`
	TLSCertFile      string        `json:"tls_cert_file"`
	TLSKeyFile       string        `json:"tls_key_file"`

	// FLEX-COLUMN Configuration
	FlexColumn *FlexColumnConfig `json:"flex_column"`

	// Autonomous maintenance: a low-priority background sweep that (a)
	// verifies block integrity and auto-repairs corruption it finds, and
	// (b) compacts blocks that haven't been written to in a while, to
	// keep disk usage down without an operator having to run `COMPACT`
	// or `REPAIR` by hand. Deliberately throttled (BlockPause between
	// each block) so it never competes meaningfully with live traffic
	// for CPU/IO — this is "administración casi autónoma", not a
	// background batch job that gets to use whatever resources it wants.
	MaintenanceEnabled     bool          `json:"maintenance_enabled"`
	MaintenanceInterval    time.Duration `json:"maintenance_interval"`
	MaintenanceBlockPause  time.Duration `json:"maintenance_block_pause"`
	MaintenanceAutoRepair  bool          `json:"maintenance_auto_repair"`
	MaintenanceAutoCompact bool          `json:"maintenance_auto_compact"`
	MaintenanceColdAfter   time.Duration `json:"maintenance_cold_after"`

	// Checkpoints: periódicamente (o vía el comando CHECKPOINT) se
	// sincronizan a disco todas las bases Badger abiertas y se sincroniza
	// y rota el WAL a un segmento nuevo (ver checkpoint.go). Esto acota
	// cuánto WAL hay que reproducir en un REDO tras un fallo -- el
	// checkpoint es el punto a partir del cual empieza esa recuperación,
	// en vez de tener que reproducir todo el historial desde el arranque.
	CheckpointEnabled  bool          `json:"checkpoint_enabled"`
	CheckpointInterval time.Duration `json:"checkpoint_interval"`

	// Auto-relations: when a user reads the same document repeatedly
	// (AutoRelationThreshold times within AutoRelationWindow), CaimanDB
	// automatically records a self-relation between that user and the
	// document, carrying a relevance score derived from access
	// frequency and recency plus a small metadata sample of the doc.
	// These relations are strictly temporal: every further access
	// slides their expiry (AutoRelationTTL) forward, and once the
	// pair stops being accessed it expires and is swept away by the
	// background cleanup loop. See relations_auto.go and the
	// SHOW AUTORELATIONS <block> command.
	AutoRelationsEnabled  bool          `json:"auto_relations_enabled"`
	AutoRelationThreshold int           `json:"auto_relation_threshold"`
	AutoRelationWindow    time.Duration `json:"auto_relation_window"`
	AutoRelationTTL       time.Duration `json:"auto_relation_ttl"`

	// Storage AI: adaptive per-block BadgerDB sizing (see
	// internal/caimandb/storage/adaptive.go). Fixes new/small blocks all
	// paying the same fixed on-disk footprint (tens of MB) regardless of
	// document count, by picking a tuning tier per block from what's
	// already on disk, capped by a shared RAM budget across every
	// currently-open block. Disabling it reproduces this project's
	// original fixed-size Badger behavior exactly.
	StorageAIEnabled     bool    `json:"storage_ai_enabled"`
	StorageAIRAMFraction float64 `json:"storage_ai_ram_fraction"`
	StorageAIMaxBudgetMB int     `json:"storage_ai_max_budget_mb"`

	// Turbo engine: adaptive worker pool + priority scheduler + an
	// auto-batching ("group commit") front door in front of standalone
	// INSERTs. Concurrent single-document INSERTs landing on the same
	// block within TurboBatchMaxWait (or until TurboBatchMaxSize
	// accumulate) are coalesced into one lock acquisition / WriteBatch
	// flush instead of one each. Disabling it reproduces the original
	// one-lock-per-INSERT behavior exactly. See internal/caimandb/turbo
	// and ops_turbo.go.
	TurboEnabled          bool          `json:"turbo_enabled"`
	TurboMinWorkers       int           `json:"turbo_min_workers"`
	TurboMaxWorkers       int           `json:"turbo_max_workers"`
	TurboBatchMaxSize     int           `json:"turbo_batch_max_size"`
	TurboBatchMaxWait     time.Duration `json:"turbo_batch_max_wait"`
	TurboBulkBatchMaxSize int           `json:"turbo_bulk_batch_max_size"`
	TurboBulkBatchMaxWait time.Duration `json:"turbo_bulk_batch_max_wait"`

	// GenerateBatchFlushSize is how many prepared documents accumulate in
	// a single Badger WriteBatch (inside handleInsertGenerate's commit
	// loop, ops_insert.go) before it's flushed and a new one is opened.
	// 0 resolves to a sensible default (see defaultGenerateBatchFlushSize
	// in ops_insert.go). Only bounds memory for a single WriteBatch, not
	// WAL fsync grouping (that's governed by WALSyncPolicy separately).
	GenerateBatchFlushSize int `json:"generate_batch_flush_size"`

	// GenerateAutoScaleMaxMultiplier caps how far runRateWatchdog
	// (cmd_insert.go) is allowed to grow the GENERATE worker pool
	// automatically, as a multiple of GOMAXPROCS -- e.g. 4 means the
	// watchdog won't push automatic scaling past GOMAXPROCS*4 workers,
	// even though maxGenerateWorkers (64) is the hard ceiling for an
	// operator who sets WORKERS explicitly. 0 resolves to a default of 4.
	// This exists because on low-core machines the watchdog's original
	// logic ("rate dropped -> add workers") could itself be the cause of
	// the rate drop once workers exceed available cores (lock contention
	// on the block being written, extra scheduling overhead) -- without a
	// ceiling tied to actual core count, that becomes a runaway loop that
	// only ever adds workers and never backs off. See runRateWatchdog's
	// doc comment in cmd_insert.go for the full explanation.
	GenerateAutoScaleMaxMultiplier int `json:"generate_autoscale_max_multiplier"`
}

type FlexColumnConfig struct {
	Enabled              bool          `json:"enabled"`
	DocumentCacheMB      int           `json:"document_cache_mb"`
	ColumnarIndexEnabled bool          `json:"columnar_index_enabled"`
	AutoDetectHotFields  bool          `json:"auto_detect_hot_fields"`
	MaterializedViews    bool          `json:"materialized_views"`
	ColumnarCompression  string        `json:"columnar_compression"`
	MaxColumnarFields    int           `json:"max_columnar_fields"`
	HotFieldThreshold    float64       `json:"hot_field_threshold"`
	WorkerCount          int           `json:"worker_count"`
	UpdateQueueSize      int           `json:"update_queue_size"`
	ViewRefreshInterval  time.Duration `json:"view_refresh_interval"`
}

func DefaultFlexColumnConfig() *FlexColumnConfig {
	return &FlexColumnConfig{
		Enabled:              true,
		DocumentCacheMB:      defaultColumnarCacheMB,
		ColumnarIndexEnabled: true,
		AutoDetectHotFields:  true,
		MaterializedViews:    true,
		ColumnarCompression:  "zstd",
		MaxColumnarFields:    maxColumnarFields,
		HotFieldThreshold:    defaultHotFieldThreshold,
		WorkerCount:          4,
		UpdateQueueSize:      10000,
		ViewRefreshInterval:  5 * time.Minute,
	}
}
