// Code generated by splitting main.go. Part of package main.
package caimandb

type Document struct {
	ID      string         `json:"_id"`
	Data    map[string]any `json:"data"`
	Meta    DocMeta        `json:"meta"`
	ShardID string         `json:"_shard_id,omitempty"`
	LargeID string         `json:"_large_id,omitempty"`
}

type DocMeta struct {
	CreatedAt int64 `json:"created_at"`
	UpdatedAt int64 `json:"updated_at"`
	Version   int64 `json:"version"`
}

// Note: BlockMeta now lives in the storage package (storage.BlockMeta),
// alongside DirectoryManager, the only place that reads/writes it.
