// Code generated by splitting main.go. Part of package main.
package caimandb

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"go.uber.org/zap"
	"net/http"
	"strings"
	"time"
)

type AdminServer struct {
	engine   *Engine
	config   *Config
	mux      *http.ServeMux
	server   *http.Server
	tokenMgr *TokenManager
}

func NewAdminServer(engine *Engine, config *Config) *AdminServer {
	as := &AdminServer{
		engine:   engine,
		config:   config,
		mux:      http.NewServeMux(),
		tokenMgr: engine.tokenManager,
	}

	as.mux.HandleFunc("/api/v1/health", as.handleHealth)
	as.mux.HandleFunc("/api/v1/status", as.handleStatus)
	as.mux.HandleFunc("/api/v1/dbs", as.handleDatabases)
	as.mux.HandleFunc("/api/v1/db/", as.handleDB)
	as.mux.HandleFunc("/api/v1/query", as.handleQuery)
	as.mux.HandleFunc("/api/v1/backup", as.handleBackup)
	as.mux.HandleFunc("/api/v1/restore", as.handleRestore)
	as.mux.HandleFunc("/api/v1/compact", as.handleCompact)
	as.mux.HandleFunc("/api/v1/users", as.handleUsers)
	as.mux.HandleFunc("/api/v1/auth/login", as.handleLogin)
	as.mux.HandleFunc("/api/v1/auth/logout", as.handleLogout)
	as.mux.HandleFunc("/api/v1/token", as.handleToken)
	as.mux.HandleFunc("/api/v1/metrics", promhttp.Handler().ServeHTTP)

	// Also expose the same console routes the query server has
	// (/query, /status, /health, /watch, /entities), reusing its exact
	// handlers (they only touch engine/config/tokenMgr, all of which
	// this admin server already has). This lets ui/ log in and work
	// against either port — the admin port (AdminPort, 1556 by
	// default) or the query port (QueryPort, 1555) — instead of only
	// working when it happens to be served from the query port. Since
	// qsShim.engine is the same root Engine (with serverMgr set), these
	// routes already resolve multi-server credentials the same way
	// as.handleQuery below does.
	qsShim := &QueryServer{engine: engine, config: config, tokenMgr: engine.tokenManager}
	as.mux.HandleFunc("/query", qsShim.handleQuery)
	as.mux.HandleFunc("/status", qsShim.handleStatus)
	as.mux.HandleFunc("/health", qsShim.handleHealth)
	as.mux.HandleFunc("/watch", qsShim.handleWatch)
	as.mux.HandleFunc("/entities", qsShim.handleEntities)

	return as
}

// resolveAdmin autentica la petición y devuelve el Engine al que debe
// enrutarse (servidor raíz o el que corresponda según las credenciales,
// cuando hay servidores adicionales aprovisionados con CREATE SERVER --
// ver server_manager.go), junto con los claims del usuario autenticado.
// Con Bearer/JWT se mantiene el comportamiento histórico (servidor
// raíz), ya que el token no lleva información de servidor en esta
// versión.
func (as *AdminServer) resolveAdmin(r *http.Request) (*Engine, *TokenClaims, bool) {
	user, pass, ok := r.BasicAuth()
	if ok {
		if as.engine.serverMgr != nil {
			if eng, u, authOK := as.engine.serverMgr.Authenticate(user, pass); authOK {
				return eng, &TokenClaims{Username: u.Username, Role: u.Role}, true
			}
			return nil, nil, false
		}
		if authOK, u := as.engine.AuthUserDetailed(user, pass); authOK {
			return as.engine, &TokenClaims{Username: u.Username, Role: u.Role}, true
		}
		return nil, nil, false
	}

	token := r.Header.Get("Authorization")
	if strings.HasPrefix(token, "Bearer ") {
		token = strings.TrimPrefix(token, "Bearer ")
		if claims, err := as.tokenMgr.ValidateToken(token); err == nil {
			return as.engine, claims, true
		}
	}

	return nil, nil, false
}

// auth conserva la firma histórica para el único caso que no necesita el
// Engine resuelto (ya cubierto por resolveAdmin en todos los demás).
func (as *AdminServer) auth(r *http.Request) (*TokenClaims, bool) {
	_, claims, ok := as.resolveAdmin(r)
	return claims, ok
}

func (as *AdminServer) handleToken(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	user, pass, ok := r.BasicAuth()
	if !ok {
		http.Error(w, "Unauthorized - Basic Auth required", http.StatusUnauthorized)
		return
	}

	var eng *Engine
	var authRole string
	if as.engine.serverMgr != nil {
		e, u, authOK := as.engine.serverMgr.Authenticate(user, pass)
		if !authOK {
			http.Error(w, "Invalid credentials", http.StatusUnauthorized)
			return
		}
		eng, authRole = e, u.Role
	} else {
		authOK, u := as.engine.AuthUserDetailed(user, pass)
		if !authOK {
			http.Error(w, "Invalid credentials", http.StatusUnauthorized)
			return
		}
		eng, authRole = as.engine, u.Role
	}

	role := authRole
	if role == "" {
		users, _ := eng.ShowUsers()
		for _, u := range users {
			if u["username"] == user {
				if r, ok := u["role"].(string); ok {
					role = r
				}
				break
			}
		}
	}
	if role == "" {
		role = RoleUser
	}

	token, err := as.tokenMgr.GenerateToken(user, user, role)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{
		"token":   token,
		"user":    user,
		"role":    role,
		"expires": time.Now().Add(as.config.TokenExpiry).Unix(),
	})
}

func (as *AdminServer) handleHealth(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{
		"status":     "ok",
		"version":    Version,
		"uptime":     time.Since(startTimeGlobal).String(),
		"max_nodes":  as.config.MaxClusterNodes,
		"max_shards": as.config.MaxShardsPerNode,
	})
}

func (as *AdminServer) handleStatus(w http.ResponseWriter, r *http.Request) {
	eng, claims, ok := as.resolveAdmin(r)
	if !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	dbs, _ := eng.ShowDBs()
	status := map[string]any{
		"version":    Version,
		"node_id":    eng.nodeID,
		"databases":  len(dbs),
		"shards":     eng.shardMgr.shardCount,
		"replicas":   eng.shardMgr.replicaCount,
		"ops":        eng.opCount.Load(),
		"memory":     getMemStats(),
		"l1_cache":   eng.l1Cache.Stats(),
		"metrics":    eng.metrics.Stats(),
		"uptime":     time.Since(eng.startupTime).Seconds(),
		"user":       claims.Username,
		"role":       claims.Role,
		"max_shards": as.config.MaxShardsPerNode,
		"max_nodes":  as.config.MaxClusterNodes,
		"flex_stats": eng.flexEngine.Stats(),
	}

	if eng.cluster != nil {
		status["cluster"] = map[string]any{
			"role":   eng.cluster.raft.State().String(),
			"leader": string(eng.cluster.raft.Leader()),
			"peers":  eng.cluster.GetPeers(),
		}
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(status)
}

func (as *AdminServer) handleDatabases(w http.ResponseWriter, r *http.Request) {
	eng, _, ok := as.resolveAdmin(r)
	if !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	switch r.Method {
	case "GET":
		dbs, err := eng.ShowDBs()
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(dbs)

	case "POST":
		var req struct {
			Name string `json:"name"`
		}
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := eng.CreateDB(req.Name); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.WriteHeader(http.StatusCreated)
		json.NewEncoder(w).Encode(map[string]string{"status": "created", "name": req.Name})

	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

func (as *AdminServer) handleDB(w http.ResponseWriter, r *http.Request) {
	eng, _, ok := as.resolveAdmin(r)
	if !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	path := strings.TrimPrefix(r.URL.Path, "/api/v1/db/")
	parts := strings.Split(path, "/")
	if len(parts) == 0 || parts[0] == "" {
		http.Error(w, "Database name required", http.StatusBadRequest)
		return
	}
	dbName := parts[0]

	switch r.Method {
	case "GET":
		info, err := eng.DescribeDB(dbName)
		if err != nil {
			http.Error(w, err.Error(), http.StatusNotFound)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(info)

	case "DELETE":
		if err := eng.DropDB(dbName); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"status": "deleted"})

	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

func (as *AdminServer) handleQuery(w http.ResponseWriter, r *http.Request) {
	eng, claims, ok := as.resolveAdmin(r)
	if !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	if r.Method != "POST" {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req struct {
		Query string `json:"query"`
		DB    string `json:"db"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	sess := &Session{
		currentDB: req.DB,
		authUser:  claims.Username,
		authRole:  claims.Role,
		token:     r.Header.Get("Authorization"),
	}

	result := parseAndExec(eng, sess, req.Query)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{
		"success": result != "ERROR",
		"result":  result,
		"db":      req.DB,
	})
}

func (as *AdminServer) handleBackup(w http.ResponseWriter, r *http.Request) {
	eng, _, ok := as.resolveAdmin(r)
	if !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	if r.Method != "POST" {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req struct {
		DB   string `json:"db"`
		File string `json:"file"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	if err := eng.Backup(req.DB, req.File); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": "backup complete"})
}

func (as *AdminServer) handleRestore(w http.ResponseWriter, r *http.Request) {
	eng, _, ok := as.resolveAdmin(r)
	if !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	if r.Method != "POST" {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req struct {
		DB   string `json:"db"`
		File string `json:"file"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	if err := eng.Restore(req.DB, req.File); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": "restore complete"})
}

func (as *AdminServer) handleCompact(w http.ResponseWriter, r *http.Request) {
	eng, _, ok := as.resolveAdmin(r)
	if !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	if r.Method != "POST" {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req struct {
		DB string `json:"db"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	rounds, err := eng.Compact(req.DB)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{
		"status": "compact complete",
		"rounds": rounds,
	})
}

func (as *AdminServer) handleUsers(w http.ResponseWriter, r *http.Request) {
	eng, claims, ok := as.resolveAdmin(r)
	if !ok {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	switch r.Method {
	case "GET":
		users, err := eng.ShowUsers()
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(users)

	case "POST":
		// Solo ADMIN/SUBADMIN pueden dar de alta usuarios en su propio
		// servidor -- esto evita que un USER/DEVELOPER autenticado use
		// este endpoint para crearse permisos más altos.
		if !IsAdminRole(claims.Role) && claims.Role != RoleSubadmin {
			http.Error(w, "Forbidden: only ADMIN or SUBADMIN can create users", http.StatusForbidden)
			return
		}
		var req struct {
			Username string `json:"username"`
			Password string `json:"password"`
			Role     string `json:"role"`
		}
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := eng.CreateUser(req.Username, req.Password, req.Role); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.WriteHeader(http.StatusCreated)
		json.NewEncoder(w).Encode(map[string]string{"status": "created"})

	default:
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
	}
}

func (as *AdminServer) handleLogin(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req struct {
		Username string `json:"username"`
		Password string `json:"password"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	var role string
	var ok bool
	if as.engine.serverMgr != nil {
		var u User
		_, u, ok = as.engine.serverMgr.Authenticate(req.Username, req.Password)
		role = u.Role
	} else {
		ok, role = as.engine.AuthUser(req.Username, req.Password)
	}
	if !ok {
		http.Error(w, "Invalid credentials", http.StatusUnauthorized)
		return
	}

	token, err := as.tokenMgr.GenerateToken(req.Username, req.Username, role)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{
		"token":   token,
		"user":    req.Username,
		"role":    role,
		"expires": time.Now().Add(as.config.TokenExpiry).Unix(),
	})
}

func (as *AdminServer) handleLogout(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	token := r.Header.Get("Authorization")
	if strings.HasPrefix(token, "Bearer ") {
		token = strings.TrimPrefix(token, "Bearer ")
		as.tokenMgr.RevokeToken(token)
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": "logged out"})
}

func (as *AdminServer) Start() {
	addr := fmt.Sprintf(":%d", as.config.AdminPort)
	as.server = &http.Server{
		Addr:         addr,
		Handler:      withCORS(as.mux),
		ReadTimeout:  30 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	safeGo("admin_server", func() {
		log().Info("Admin server started", zap.Int("port", as.config.AdminPort))
		if as.config.TLSEnabled {
			if err := as.server.ListenAndServeTLS(as.config.TLSCertFile, as.config.TLSKeyFile); err != nil && err != http.ErrServerClosed {
				log().Error("Admin server failed", zap.Error(err))
			}
		} else {
			if err := as.server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
				log().Error("Admin server failed", zap.Error(err))
			}
		}
	})
}

func (as *AdminServer) Stop() {
	if as.server != nil {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		as.server.Shutdown(ctx)
	}
}
