// Code generated by splitting main.go. Part of package main.
package caimandb

import (
	"fmt"

	"caimandb/internal/caimandb/turbo"
	"caimandb/internal/caimandb/wal"
)

// newTurboCoordinator builds the turbo engine infrastructure (adaptive
// worker pool, priority scheduler, bulk-mode flag) and the auto-batching
// front doors that sit in front of the engine's existing write paths. It's
// deliberately a thin layer: all it does is coalesce what look like
// independent single-document requests into fewer calls to the storage
// paths that already exist (insertBatchLocalDetailed / InsertBatch), which
// already do one lock acquisition, one WriteBatch and (in cluster mode)
// one Raft round-trip per group instead of per document.
func newTurboCoordinator(e *Engine) *Engine {
	e.turbo = turbo.New(turbo.Config{
		MinWorkers: e.config.TurboMinWorkers,
		MaxWorkers: e.config.TurboMaxWorkers,

		BatchMaxSize: e.config.TurboBatchMaxSize,
		BatchMaxWait: e.config.TurboBatchMaxWait,

		BulkBatchMaxSize: e.config.TurboBulkBatchMaxSize,
		BulkBatchMaxWait: e.config.TurboBulkBatchMaxWait,
	})

	maxSize, maxWait := e.turbo.BatchThresholds()
	e.turboInserts = turbo.NewBatcherGroup[map[string]any](maxSize, maxWait, e.flushTurboInsertBatch)

	return e
}

// flushTurboInsertBatch is the BatcherGroup flush callback for
// e.turboInserts: it's handed every document that landed in the same
// (db, block) batch window and must insert all of them and report one
// error per document, in the same order.
func (e *Engine) flushTurboInsertBatch(key string, docs []map[string]any) []error {
	dbName, block, ok := splitTurboKey(key)
	if !ok {
		errs := make([]error, len(docs))
		for i := range errs {
			errs[i] = fmt.Errorf("invalid turbo batch key: %q", key)
		}
		return errs
	}

	_, errs := e.insertBatchLocalDetailed(dbName, block, docs)
	return errs
}

func turboKey(dbName, block string) string {
	return dbName + "\x00" + block
}

func splitTurboKey(key string) (dbName, block string, ok bool) {
	for i := 0; i < len(key); i++ {
		if key[i] == 0 {
			return key[:i], key[i+1:], true
		}
	}
	return "", "", false
}

// InsertFast is a drop-in alternative to Insert for standalone (non-Raft)
// installations: it resolves the document's ID exactly like Insert does,
// then hands the document to the turbo auto-batcher instead of writing it
// immediately on its own. Concurrent InsertFast calls landing on the same
// (db, block) within a short window (see TurboBatchMaxWait /
// TurboBulkBatchMaxWait) are grouped into a single insertBatchLocalDetailed
// call -- one lock acquisition and one WriteBatch flush for the whole
// group -- instead of each paying for its own. A caller making a single,
// isolated call still gets a normal *Document back; it just pays a few
// hundred microseconds of extra scheduling latency for the batching hop
// even when nothing else is happening to batch with.
//
// Raft-clustered installations don't use this path: InsertFast falls back
// to Insert (which already routes through Raft) whenever the engine has an
// active cluster, since the turbo batcher's flush function writes directly
// to local storage and does not go through consensus.
//
// Known trade-off: because insertBatchLocalDetailed reports one error per
// document, a rare storage-level failure affecting only one document in a
// multi-document batch is reported only for that document -- callers whose
// requests happen to land in the same batch as a failing one are
// unaffected by it. This mirrors the aggregate-result trade-off the
// existing InsertBatch/IMPORT paths already make for bulk loads.
func (e *Engine) InsertFast(dbName, block string, data map[string]any) (*Document, error) {
	if e.turbo == nil || !e.config.TurboEnabled || (e.cluster != nil && e.cluster.IsLeader() && !e.cluster.IsSingleNode()) {
		return e.Insert(dbName, block, data)
	}

	id := resolveDocID(data)
	if id == "" {
		id = newID()
	}
	data["id"] = id

	if err := e.turboInserts.Submit(turboKey(dbName, block), data); err != nil {
		return nil, err
	}

	shardID := e.shardMgr.GetShardForDoc(dbName, block, id)
	return &Document{ID: id, Data: data, ShardID: shardID}, nil
}

// SetBulkMode turns turbo bulk-load mode on or off. While on, the turbo
// insert batcher uses wider (TurboBulkBatchMaxSize/TurboBulkBatchMaxWait)
// thresholds for bigger, less frequent batches, and the WAL's fsync policy
// is relaxed to WALSyncInterval for the duration (restored to whatever it
// was before when bulk mode is turned back off) so a long bulk load isn't
// paying for an fsync per small group the whole way through.
func (e *Engine) SetBulkMode(on bool) {
	if e.turbo == nil {
		return
	}
	if on {
		e.turbo.Bulk.Enable()
		if e.wal != nil {
			e.bulkModePrevWALPolicy = e.wal.SyncPolicy()
			e.wal.SetSyncPolicy(wal.WALSyncInterval)
		}
	} else {
		e.turbo.Bulk.Disable()
		if e.wal != nil {
			e.wal.SetSyncPolicy(e.bulkModePrevWALPolicy)
		}
	}
	if e.pool != nil {
		// Only affects the ONE-TIME tier decision for blocks opened while
		// bulk mode is on (see pickTierLocked's doc comment) -- never
		// touches a block that's already open.
		e.pool.SetBulkModeHint(on)
	}
	if e.changeBus != nil {
		// See ChangeBus.Publish's doc comment: only ever skips work that
		// would otherwise be unobservable (no subscriber connected), and
		// is re-checked on every single Publish call, so this is safe to
		// flip at any time without coordinating with in-flight inserts.
		e.changeBus.SetBulkModeHint(on)
	}
	maxSize, maxWait := e.turbo.BatchThresholds()
	e.turboInserts.SetThresholds(maxSize, maxWait)
}

// TurboStats returns a snapshot of turbo engine activity (worker pool,
// scheduler, bulk mode, insert batcher) for STATUS/diagnostics.
func (e *Engine) TurboStats() map[string]any {
	if e.turbo == nil {
		return map[string]any{"enabled": false}
	}
	stats := e.turbo.Stats()
	stats["enabled"] = e.config.TurboEnabled
	stats["insert_batcher"] = e.turboInserts.Stats()
	return stats
}
