// Code generated by splitting main.go. Part of package main.
package caimandb

import (
	"caimandb/internal/caimandb/storage"
	"caimandb/internal/caimandb/query"
	"caimandb/internal/caimandb/metrics"
	"context"
	"encoding/json"
	badger "github.com/dgraph-io/badger/v4"
	"go.uber.org/zap"
	"golang.org/x/sync/errgroup"
	"strconv"
	"strings"
	"sync"
	"time"

	"caimandb/internal/caimandb/parse"
)

type Query struct {
	Filters    []Filter
	// Where, when set, is the full WHERE-clause expression tree (see
	// internal/caimandb/parse/ast.go) and takes precedence over Filters
	// for matching: it supports parentheses and correct AND/OR/NOT
	// precedence, which a flat []Filter cannot express. Filters is
	// still populated alongside it (best-effort, top-level AND-chain
	// only) purely so index selection in QueryOptimizer.AnalyzeQuery
	// keeps working unchanged. Callers that don't build a Where tree
	// (JOIN, transactions, admin commands not yet migrated) leave this
	// nil and get the historical flat-list evaluation, unchanged.
	Where      *parse.Expr
	Select     []string
	// SelectItems is the parsed form of Select: each entry is classified
	// as a plain field/path, a COUNT(field) aggregate, or a simple
	// two-operand arithmetic expression (see select_expr.go). Populated
	// by buildFindQuery alongside Select; Select itself is left
	// unchanged so callers that only care about plain projection (or
	// that build a Query without going through buildFindQuery) keep
	// working exactly as before.
	SelectItems []query.SelectItem
	Exclude     []string
	Sort        []SortField
	// GroupBy/Having implement FIND ... GROUP BY <fields> [HAVING ...].
	// When GroupBy is set, postProcessDocs collapses the matched
	// documents into one row per distinct GroupBy value combination
	// (see group_by.go) instead of returning them individually.
	GroupBy []string
	Having  *parse.Expr
	Limit   int
	Offset  int
	UseIndex   bool
	PreferScan bool
	ShardID    string
	Timeout    time.Duration
}

type Filter struct {
	Field  string
	Op     string
	Value  any
	Value2 any
	Values []any
	Logic  string
}

type SortField struct {
	Field string
	Desc  bool
}

type QueryResult struct {
	Docs      []Document    `json:"docs"`
	Total     int64         `json:"total"`
	Scanned   int64         `json:"scanned"`
	IndexUsed string        `json:"index_used"`
	Took      time.Duration `json:"took"`
}

func (e *Engine) Find(dbName, block string, q *Query) (*QueryResult, error) {
	start := time.Now()
	defer func() {
		e.metrics.RecordQuery(time.Since(start))
		metrics.MetricActiveQueries.Dec()
	}()
	metrics.MetricActiveQueries.Inc()

	if !e.dirMgr.BlockExists(dbName, block) {
		return nil, ErrBlockNotFound
	}

	// Try FLEX-COLUMN acceleration first
	if e.flexEngine != nil && e.flexEngine.config.Enabled {
		result, err := e.flexEngine.QueryWithColumnar(dbName, block, q)
		if err == nil && result != nil && len(result.Docs) > 0 {
			return result, nil
		}
	}

	ctx := context.Background()
	if q.Timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, q.Timeout)
		defer cancel()
	} else if e.config.QueryTimeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, e.config.QueryTimeout)
		defer cancel()
	}

	db, err := e.pool.OpenBlock(dbName, block)
	if err != nil {
		return nil, err
	}

	// Block-level read lock, matching the write lock InsertBatch takes on
	// the same key (dbName + block). Reads previously took no lock at
	// all here, which is fine while a Badger handle just stays open for
	// its whole life -- but it means any future mechanism that closes and
	// reopens a block's handle in place (e.g. adaptive resize) has no
	// read lock to synchronize against, and could yank the handle out
	// from under an in-flight Find. This doesn't block concurrent reads
	// against each other (RWMutex), only against a future writer of that
	// kind.
	lockKey := dbName + "\x00" + block
	e.lockManager.RLock(lockKey)
	defer e.lockManager.RUnlock(lockKey)

	var docIDs []string
	var scanAll bool
	var indexUsed string

	if !q.PreferScan && len(q.Filters) > 0 {
		plan := e.queryOpt.AnalyzeQuery(q.Filters)
		if plan.UseIndex && (q.UseIndex || !q.PreferScan) {
			pageSize := q.Limit
			if pageSize <= 0 {
				pageSize = 10000
			}
			result, err := e.lookupByIndex(dbName, block, plan.IndexField, plan.IndexValue, 0, pageSize)
			if err == nil && len(result.DocIDs) > 0 {
				ids := result.DocIDs
				used := plan.IndexField

				// Fold in a bounded number of the next-best index
				// candidates by intersecting doc-ID sets, instead of
				// only ever probing the single top-ranked field and
				// leaving every other indexed equality filter to be
				// re-checked later the expensive way (fetch the
				// document, then matchesQuery). Each extra lookup here
				// is a real Badger prefix scan, so this stops once the
				// set is already small or a small cap of extra
				// candidates has been tried, whichever comes first.
				const maxExtraCandidates = 2
				tried := 0
				for _, c := range plan.Candidates[1:] {
					if len(ids) <= 1 || tried >= maxExtraCandidates {
						break
					}
					tried++
					extra, err := e.lookupByIndex(dbName, block, c.Field, c.Value, 0, pageSize)
					if err != nil || len(extra.DocIDs) == 0 {
						continue
					}
					ids = intersectIDs(ids, extra.DocIDs)
					used += "+" + c.Field
				}

				docIDs = ids
				scanAll = false
				indexUsed = used
			}
		}
	}

	if scanAll || len(docIDs) == 0 {
		docIDs = nil
		indexUsed = "full_scan"
		result, err := e.scanBlock(ctx, dbName, block, q, db)
		if err == nil {
			e.intelEngine.RecordQuery(&QueryRecord{
				DB:        dbName,
				Block:     block,
				Filters:   q.Filters,
				Duration:  result.Took,
				Timestamp: time.Now(),
				IndexUsed: result.IndexUsed,
				Scanned:   result.Scanned,
				Returned:  result.Total,
			})
			e.updateDBStats(dbName, result)
			metrics.MetricQueryLatency.WithLabelValues(dbName, block, "scan").Observe(result.Took.Seconds())
		}
		return result, err
	}

	var docs []Document
	var scanned int64

	relDef, _ := e.relMgr.Get(dbName, block)
	neededAliases := filterAliasRoots(q, relDef)

	// errgroup.WithContext replaces the previous sem-channel + WaitGroup
	// pair: SetLimit(1000) gives the same "at most 1000 doc fetches in
	// flight" bound, and deriving the group's context from ctx means a
	// caller cancellation (client disconnect, timeout) now also stops any
	// fetches that haven't started yet instead of only being checked at
	// the top of this loop.
	g, gctx := errgroup.WithContext(ctx)
	g.SetLimit(1000)
	var mu sync.Mutex

	for _, id := range docIDs {
		if gctx.Err() != nil {
			break
		}

		docID := id
		g.Go(func() error {
			defer func() {
				if r := recover(); r != nil {
					log().Error("find_fetch_doc panic recovered", zap.Any("panic", r))
				}
			}()

			ck := e.cacheKey(dbName, block, docID)
			var doc Document
			var found bool

			if raw, ok := e.l1Cache.Get(ck); ok {
				if json.Unmarshal(raw, &doc) == nil {
					found = true
				}
			}

			if !found {
				err := txHelper.SafeView(db, func(txn *badger.Txn) error {
					item, err := txn.Get(docKey(block, docID))
					if err != nil {
						return err
					}
					return item.Value(func(v []byte) error {
						if e.config.CompressLargeDocs && len(v) > 0 {
							if decompressed, err := storage.DecompressData(v); err == nil {
								e.l1Cache.Set(ck, decompressed)
								return json.Unmarshal(decompressed, &doc)
							}
						}
						e.l1Cache.Set(ck, v)
						return json.Unmarshal(v, &doc)
					})
				})
				if err != nil {
					return nil
				}
			}

			filterDoc := doc
			if len(neededAliases) > 0 {
				filterDoc = e.attachRelationsForFilter(doc, relDef, neededAliases)
			}

			mu.Lock()
			scanned++
			if matchesQuery(filterDoc, q) {
				if q.ShardID == "" || doc.ShardID == q.ShardID {
					docs = append(docs, doc)
				}
			}
			mu.Unlock()
			return nil
		})
	}
	_ = g.Wait()

	if ctx.Err() != nil {
		return nil, ctx.Err()
	}

	total := int64(len(docs))
	docs = e.postProcessDocs(dbName, block, docs, q)

	result := &QueryResult{
		Docs:      docs,
		Total:     total,
		Scanned:   scanned,
		IndexUsed: indexUsed,
		Took:      time.Since(start),
	}

	e.intelEngine.RecordQuery(&QueryRecord{
		DB:        dbName,
		Block:     block,
		Filters:   q.Filters,
		Duration:  result.Took,
		Timestamp: time.Now(),
		IndexUsed: result.IndexUsed,
		Scanned:   result.Scanned,
		Returned:  result.Total,
	})
	e.updateDBStats(dbName, result)
	metrics.MetricQueryLatency.WithLabelValues(dbName, block, "index").Observe(result.Took.Seconds())

	return result, nil
}

func (e *Engine) scanBlock(ctx context.Context, dbName, block string, q *Query, db *badger.DB) (*QueryResult, error) {
	start := time.Now()
	prefix := docKeyPrefix(block)

	var matched []Document
	var scanned int64

	relDef, _ := e.relMgr.Get(dbName, block)
	neededAliases := filterAliasRoots(q, relDef)

	limit := q.Limit
	offset := q.Offset
	if limit <= 0 {
		limit = 10000
	}
	if offset < 0 {
		offset = 0
	}

	err := txHelper.SafeView(db, func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.PrefetchSize = 100
		opts.PrefetchValues = true
		it := txn.NewIterator(opts)
		defer it.Close()

		skipCount := 0

		for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
			select {
			case <-ctx.Done():
				return ctx.Err()
			default:
			}

			if skipCount < offset {
				skipCount++
				continue
			}

			if len(matched) >= limit && limit > 0 {
				break
			}

			var doc Document
			item := it.Item()
			if item == nil {
				continue
			}
			err := item.Value(func(v []byte) error {
				if e.config.CompressLargeDocs && len(v) > 0 {
					if decompressed, err := storage.DecompressData(v); err == nil {
						return json.Unmarshal(decompressed, &doc)
					}
				}
				return json.Unmarshal(v, &doc)
			})
			if err != nil {
				continue
			}

			scanned++

			if q.ShardID != "" && doc.ShardID != q.ShardID {
				continue
			}

			filterDoc := doc
			if len(neededAliases) > 0 {
				filterDoc = e.attachRelationsForFilter(doc, relDef, neededAliases)
			}

			if matchesQuery(filterDoc, q) {
				matched = append(matched, doc)
			}
		}
		return nil
	})

	if err != nil {
		return nil, err
	}

	total := int64(len(matched))
	docs := e.postProcessDocs(dbName, block, matched, q)

	return &QueryResult{
		Docs:      docs,
		Total:     total,
		Scanned:   scanned,
		IndexUsed: "full_scan",
		Took:      time.Since(start),
	}, nil
}

func (e *Engine) postProcessDocs(dbName, block string, docs []Document, q *Query) []Document {
	if len(q.GroupBy) > 0 {
		docs = e.groupDocs(dbName, block, docs, q)
		if len(q.Sort) > 0 {
			sortDocs(docs, q.Sort)
		}
		if q.Limit > 0 && len(docs) > q.Limit {
			docs = docs[:q.Limit]
		}
		return docs
	}

	// Computed SELECT entries (COUNT(field) AS alias, arithmetic like
	// "duration_minutes / 60 as hours") get evaluated and written into
	// each doc's Data under their alias *before* sorting/projection, so
	// ORDER BY and the final field list can reference the alias exactly
	// like any other field.
	if len(q.SelectItems) > 0 {
		hasComputed := false
		for _, it := range q.SelectItems {
			if it.Kind != query.SelectPlain {
				hasComputed = true
				break
			}
		}
		if hasComputed {
			for i := range docs {
				docs[i].Data = query.ApplySelectExprs(docs[i].Data, q.SelectItems)
			}
			q.Select = query.SelectProjectFields(q.SelectItems)
		}
	}

	if len(q.Sort) > 0 {
		sortDocs(docs, q.Sort)
	}

	if len(q.Select) > 0 || len(q.Exclude) > 0 {
		docs = e.resolveRelations(dbName, block, docs, q)
	}

	if q.Limit > 0 && len(docs) > q.Limit {
		docs = docs[:q.Limit]
	}

	return docs
}

func (e *Engine) FindByID(dbName, block, id string) (*Document, bool) {
	if !e.dirMgr.BlockExists(dbName, block) {
		return nil, false
	}

	ck := e.cacheKey(dbName, block, id)
	if raw, ok := e.l1Cache.Get(ck); ok {
		var doc Document
		if json.Unmarshal(raw, &doc) == nil {
			if doc.LargeID != "" && e.externalStore != nil {
				if externalData, err := e.externalStore.Load(doc.LargeID); err == nil {
					var fullDoc Document
					if json.Unmarshal(externalData, &fullDoc) == nil {
						return &fullDoc, true
					}
				}
			}
			metrics.MetricCacheHits.Inc()
			return &doc, true
		}
	}

	db, err := e.pool.OpenBlock(dbName, block)
	if err != nil {
		return nil, false
	}

	var doc Document
	err = txHelper.SafeView(db, func(txn *badger.Txn) error {
		item, err := txn.Get(docKey(block, id))
		if err != nil {
			return err
		}
		return item.Value(func(v []byte) error {
			if e.config.CompressLargeDocs && len(v) > 0 {
				if decompressed, err := storage.DecompressData(v); err == nil {
					e.l1Cache.Set(ck, decompressed)
					return json.Unmarshal(decompressed, &doc)
				}
			}
			e.l1Cache.Set(ck, v)
			return json.Unmarshal(v, &doc)
		})
	})
	if err != nil {
		metrics.MetricCacheMisses.Inc()
		return nil, false
	}

	if doc.LargeID != "" && e.externalStore != nil {
		if externalData, err := e.externalStore.Load(doc.LargeID); err == nil {
			var fullDoc Document
			if json.Unmarshal(externalData, &fullDoc) == nil {
				metrics.MetricCacheHits.Inc()
				return &fullDoc, true
			}
		}
	}

	metrics.MetricCacheHits.Inc()
	return &doc, true
}

func (e *Engine) updateDBStats(dbName string, result *QueryResult) {
	if stats, ok := e.intelEngine.stats[dbName]; ok {
		stats.QueryCount++
		stats.AvgQueryTime = (stats.AvgQueryTime*float64(stats.QueryCount-1) + float64(result.Took.Milliseconds())) / float64(stats.QueryCount)
		if result.IndexUsed != "full_scan" {
			stats.IndexHitRate = (stats.IndexHitRate*float64(stats.QueryCount-1) + 1) / float64(stats.QueryCount)
		} else {
			stats.IndexHitRate = (stats.IndexHitRate*float64(stats.QueryCount-1) + 0) / float64(stats.QueryCount)
		}
		cacheStats := e.l1Cache.Stats()
		if hitRatio, ok := cacheStats["hit_ratio"].(string); ok {
			if val, err := strconv.ParseFloat(strings.TrimSuffix(hitRatio, "%"), 64); err == nil {
				stats.CacheHitRate = val / 100
			}
		}
	}
}
