// Code generated by splitting main.go. Part of package main.
package caimandb

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"time"
)

// BulkImportOptions controls Engine.BulkImportReader.
type BulkImportOptions struct {
	// BatchSize is how many decoded documents are grouped into a single
	// insertBatchLocalDetailed call (one block-lock acquisition, one
	// Badger write-batch, one WAL append per doc, inline indexing).
	// Defaults to 20000 when <= 0 -- deliberately larger than
	// InsertBatch's own MaxBatchSize-driven chunking default (10000),
	// since a caller reaching for BulkImportReader has already opted
	// into a bulk load and is trading a little extra memory (one
	// BatchSize-sized slice of decoded docs at a time) and per-chunk
	// latency for materially fewer chunks over a very large file.
	BatchSize int

	// Format selects how the reader is decoded:
	//   "ndjson" (default) -- one JSON object per line, the standard
	//     bulk-load format; a blank line is skipped.
	//   "array" -- a single top-level JSON array of objects, decoded
	//     with a streaming token-based decoder so even a huge array file
	//     is never held in memory beyond the current batch.
	Format string

	// ContinueOnError, when true (the default), keeps importing after a
	// document fails to decode or insert, collecting up to
	// MaxErrorSamples example messages and an exact Errors count. When
	// false, the first error stops the import immediately -- everything
	// already flushed in earlier chunks stays committed, since bulk
	// import is only transactional within a single chunk's own
	// write-batch, never across the whole file.
	ContinueOnError bool

	// MaxErrorSamples caps how many individual error messages are kept
	// in the final report; defaults to 20 when <= 0. The returned Errors
	// *count* is always exact regardless of this cap -- only the number
	// of retained example messages is limited, so a file with a million
	// malformed lines doesn't also cost a million-string slice.
	MaxErrorSamples int

	// Progress, if set, is called synchronously after every flushed
	// chunk with the running totals so a caller can report progress on
	// a very large import without waiting for the whole file to finish.
	Progress func(BulkImportProgress)

	// SkipBulkModeToggle, when true, leaves the engine's current BULK
	// MODE / WAL sync policy untouched instead of enabling bulk mode for
	// the duration of this import. Useful when a caller is running
	// several imports concurrently under a BULK MODE ON they manage
	// themselves, since a plain enable/disable here would otherwise
	// switch bulk mode back off out from under a sibling import as soon
	// as this one finishes.
	SkipBulkModeToggle bool
}

// BulkImportProgress is one snapshot handed to BulkImportOptions.Progress.
type BulkImportProgress struct {
	Decoded  int64
	Inserted int64
	Errors   int64
	Elapsed  time.Duration
}

// BulkImportResult is BulkImportReader's final report.
type BulkImportResult struct {
	Decoded      int64
	Inserted     int64
	Errors       int64
	ErrorSamples []string
	Took         time.Duration
}

// BulkImportReader streams documents from r into dbName/block in large
// batches, reusing the exact same write-batch/WAL/index/compression path
// as InsertBatch (insertBatchLocalDetailed) for every chunk. This adds no
// new on-disk format or indexing logic -- it's a large-batch-friendly
// front door around a path that already exists, built to keep both memory
// and per-item overhead flat regardless of file size:
//
//   - Never holds the whole input in memory: only one BatchSize-sized
//     slice of already-decoded documents at a time.
//   - Never holds the whole result in memory: only aggregate counters
//     plus a small, capped sample of error messages.
//   - Pays for one block-lock acquisition and one Badger write-batch
//     flush cadence per BatchSize documents (insertBatchLocalDetailed
//     itself flushes every 1000 within that), instead of one lock
//     acquisition per document the way a loop of single Insert() calls
//     would.
//   - Automatically widens the turbo batcher's thresholds and relaxes
//     the WAL's fsync policy for the duration (see Engine.SetBulkMode),
//     unless the caller opted out via SkipBulkModeToggle.
//
// The target block is created if it doesn't exist yet, matching
// InsertBatch's own behavior.
func (e *Engine) BulkImportReader(dbName, block string, r io.Reader, opts BulkImportOptions) (*BulkImportResult, error) {
	if opts.BatchSize <= 0 {
		opts.BatchSize = 20000
	}
	if opts.MaxErrorSamples <= 0 {
		opts.MaxErrorSamples = 20
	}
	format := opts.Format
	if format == "" {
		format = "ndjson"
	}
	if format != "ndjson" && format != "array" {
		return nil, fmt.Errorf("unsupported bulk import format %q -- expected \"ndjson\" or \"array\"", format)
	}

	if !opts.SkipBulkModeToggle {
		e.SetBulkMode(true)
		defer e.SetBulkMode(false)
	}

	if err := e.dirMgr.CreateBlockDirectories(dbName, block); err != nil {
		return nil, err
	}

	start := time.Now()
	res := &BulkImportResult{}
	batch := make([]map[string]any, 0, opts.BatchSize)

	flush := func() {
		if len(batch) == 0 {
			return
		}
		inserted, errs := e.insertBatchLocalDetailed(dbName, block, batch)
		res.Inserted += inserted
		for _, err := range errs {
			if err == nil {
				continue
			}
			res.Errors++
			if len(res.ErrorSamples) < opts.MaxErrorSamples {
				res.ErrorSamples = append(res.ErrorSamples, err.Error())
			}
		}
		batch = make([]map[string]any, 0, opts.BatchSize)
		if opts.Progress != nil {
			opts.Progress(BulkImportProgress{
				Decoded:  res.Decoded,
				Inserted: res.Inserted,
				Errors:   res.Errors,
				Elapsed:  time.Since(start),
			})
		}
	}

	addDoc := func(doc map[string]any) {
		res.Decoded++
		batch = append(batch, doc)
		if len(batch) >= opts.BatchSize {
			flush()
		}
	}

	var decodeErr error
	if format == "ndjson" {
		decodeErr = decodeNDJSONDocs(r, opts, res, addDoc)
	} else {
		decodeErr = decodeJSONArrayDocs(r, opts, res, addDoc)
	}

	// Flush whatever's pending regardless of how decoding ended, so a
	// ContinueOnError=false stop (or an I/O error) still commits every
	// document decoded before the failure instead of discarding a
	// partially-filled final batch.
	flush()
	res.Took = time.Since(start)

	if decodeErr != nil {
		return res, decodeErr
	}
	return res, nil
}

// decodeNDJSONDocs reads one JSON object per line from r, calling addDoc
// for each successfully decoded document.
func decodeNDJSONDocs(r io.Reader, opts BulkImportOptions, res *BulkImportResult, addDoc func(map[string]any)) error {
	scanner := bufio.NewScanner(r)
	// A document can legitimately be larger than bufio.Scanner's 64KB
	// default token limit; grow it well past any reasonable single-line
	// document instead of silently erroring out on the first large one.
	scanner.Buffer(make([]byte, 0, 1<<20), 64<<20)

	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := scanner.Bytes()
		if len(bytes.TrimSpace(line)) == 0 {
			continue
		}
		var doc map[string]any
		dec := json.NewDecoder(bytes.NewReader(line))
		dec.UseNumber()
		if err := dec.Decode(&doc); err != nil {
			res.Errors++
			if len(res.ErrorSamples) < opts.MaxErrorSamples {
				res.ErrorSamples = append(res.ErrorSamples, fmt.Sprintf("line %d: %v", lineNo, err))
			}
			if !opts.ContinueOnError {
				return fmt.Errorf("line %d: %w", lineNo, err)
			}
			continue
		}
		addDoc(doc)
	}
	return scanner.Err()
}

// decodeJSONArrayDocs reads a single top-level JSON array of objects from
// r using a streaming token decoder, calling addDoc for each element.
func decodeJSONArrayDocs(r io.Reader, opts BulkImportOptions, res *BulkImportResult, addDoc func(map[string]any)) error {
	dec := json.NewDecoder(r)
	dec.UseNumber()

	tok, err := dec.Token()
	if err != nil {
		return err
	}
	if delim, ok := tok.(json.Delim); !ok || delim != '[' {
		return fmt.Errorf("expected a top-level JSON array")
	}

	idx := 0
	for dec.More() {
		idx++
		var doc map[string]any
		if err := dec.Decode(&doc); err != nil {
			res.Errors++
			if len(res.ErrorSamples) < opts.MaxErrorSamples {
				res.ErrorSamples = append(res.ErrorSamples, fmt.Sprintf("element %d: %v", idx, err))
			}
			if !opts.ContinueOnError {
				return fmt.Errorf("element %d: %w", idx, err)
			}
			continue
		}
		addDoc(doc)
	}
	return nil
}
