// Code generated by splitting main.go. Part of package main.
package caimandb

import (
	"fmt"
	"strings"

	"caimandb/internal/caimandb/parse"
)

// matchesQuery decides whether doc satisfies q. When q.Where is set
// (currently: queries built by handleFind/handleSearch) it evaluates
// the full WHERE-clause expression tree, which correctly supports
// parentheses and AND/OR/NOT precedence. Otherwise it falls back to
// matchesFilters, the historical flat left-to-right evaluation, so
// every other command that still builds a bare []Filter (JOIN,
// transactions, CLEAR/COUNT/aggregate, admin commands) keeps behaving
// exactly as it did before this file changed.
func matchesQuery(doc Document, q *Query) bool {
	if q.Where != nil {
		return evalExpr(doc, q.Where)
	}
	return matchesFilters(doc, q.Filters)
}

// evalExpr walks a parse.Expr tree (see internal/caimandb/parse/ast.go)
// and evaluates it against doc. Leaf nodes reuse matchFilter, the same
// single-condition matcher the flat filter list already used, so a
// leaf behaves identically whether it arrived via the old []Filter
// path or the new AST.
func evalExpr(doc Document, e *parse.Expr) bool {
	if e == nil {
		return true
	}
	switch e.Kind {
	case parse.KindAnd:
		return evalExpr(doc, e.Left) && evalExpr(doc, e.Right)
	case parse.KindOr:
		return evalExpr(doc, e.Left) || evalExpr(doc, e.Right)
	case parse.KindNot:
		return !evalExpr(doc, e.Child)
	default:
		return matchFilter(doc, Filter{
			Field:  e.Field,
			Op:     e.Op,
			Value:  e.Value,
			Value2: e.Value2,
			Values: e.Values,
		})
	}
}

func matchesFilters(doc Document, filters []Filter) bool {
	if len(filters) == 0 {
		return true
	}
	result := false
	first := true
	for _, f := range filters {
		m := matchFilter(doc, f)
		if first {
			result = m
			first = false
		} else if strings.EqualFold(f.Logic, "OR") {
			result = result || m
		} else {
			result = result && m
		}
	}
	return result
}

// matchFilter evaluates a single "field op value" condition against doc.
// f.Field is resolved via getNestedValues rather than a plain single-value
// lookup: for an ordinary scalar/nested-object path this behaves exactly
// like before (one value, matched once), but when the path passes through
// an array of objects -- e.g. "genres.name" after a one-to-many RELATE
// alias has been attached to doc.Data by attachRelationsForFilter, or any
// plain array-of-objects field -- it matches if *any* element satisfies
// the condition, the usual join semantics for a one-to-many relationship
// in a WHERE clause.
func matchFilter(doc Document, f Filter) bool {
	vals := getNestedValues(doc.Data, f.Field)
	if len(vals) <= 1 {
		var val any
		if len(vals) == 1 {
			val = vals[0]
		}
		return matchValue(val, f)
	}
	for _, val := range vals {
		if matchValue(val, f) {
			return true
		}
	}
	return false
}

func matchValue(val any, f Filter) bool {
	switch strings.ToUpper(f.Op) {
	case "=", "==":
		return fmt.Sprint(val) == fmt.Sprint(f.Value)
	case "!=", "<>":
		return fmt.Sprint(val) != fmt.Sprint(f.Value)
	case ">":
		return compareNumbers(val, f.Value) > 0
	case "<":
		return compareNumbers(val, f.Value) < 0
	case ">=":
		return compareNumbers(val, f.Value) >= 0
	case "<=":
		return compareNumbers(val, f.Value) <= 0
	case "LIKE":
		s := strings.ToLower(fmt.Sprint(val))
		p := strings.ToLower(fmt.Sprint(f.Value))
		if strings.HasPrefix(p, "%") && strings.HasSuffix(p, "%") {
			return strings.Contains(s, strings.Trim(p, "%"))
		} else if strings.HasPrefix(p, "%") {
			return strings.HasSuffix(s, strings.TrimPrefix(p, "%"))
		} else if strings.HasSuffix(p, "%") {
			return strings.HasPrefix(s, strings.TrimSuffix(p, "%"))
		}
		return s == p
	case "NOT LIKE":
		s := strings.ToLower(fmt.Sprint(val))
		p := strings.ToLower(fmt.Sprint(f.Value))
		if strings.HasPrefix(p, "%") && strings.HasSuffix(p, "%") {
			return !strings.Contains(s, strings.Trim(p, "%"))
		} else if strings.HasPrefix(p, "%") {
			return !strings.HasSuffix(s, strings.TrimPrefix(p, "%"))
		} else if strings.HasSuffix(p, "%") {
			return !strings.HasPrefix(s, strings.TrimSuffix(p, "%"))
		}
		return s != p
	case "CONTAINS":
		return strings.Contains(strings.ToLower(fmt.Sprint(val)), strings.ToLower(fmt.Sprint(f.Value)))
	case "NOT CONTAINS":
		return !strings.Contains(strings.ToLower(fmt.Sprint(val)), strings.ToLower(fmt.Sprint(f.Value)))
	case "EXISTS":
		return val != nil
	case "IN":
		sv := fmt.Sprint(val)
		for _, v := range f.Values {
			if fmt.Sprint(v) == sv {
				return true
			}
		}
		return false
	case "NOT IN":
		sv := fmt.Sprint(val)
		for _, v := range f.Values {
			if fmt.Sprint(v) == sv {
				return false
			}
		}
		return true
	case "BETWEEN":
		return compareNumbers(val, f.Value) >= 0 && compareNumbers(val, f.Value2) <= 0
	case "STARTS WITH":
		return strings.HasPrefix(fmt.Sprint(val), fmt.Sprint(f.Value))
	case "ENDS WITH":
		return strings.HasSuffix(fmt.Sprint(val), fmt.Sprint(f.Value))
	case "IS NULL":
		return val == nil || fmt.Sprint(val) == ""
	case "IS NOT NULL":
		return val != nil && fmt.Sprint(val) != ""
	}
	return false
}

func compareNumbers(a, b any) int {
	fa := toF64(a)
	fb := toF64(b)

	if fa != 0 || fb != 0 {
		if fa < fb {
			return -1
		}
		if fa > fb {
			return 1
		}
		return 0
	}

	sa := fmt.Sprint(a)
	sb := fmt.Sprint(b)
	return strings.Compare(sa, sb)
}
