// Code generated by splitting main.go. Part of package main.
package caimandb

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
)

// RelationTarget describes one target block that a source block relates
// to, as registered via RELATE <block> USE <target1>,<target2>,...
//
// Targets may live in a different database than the source block, using
// "db.block" syntax in RELATE (e.g. "crm.customers"); a bare block name
// ("customers") targets a block in the same database as the source.
type RelationTarget struct {
	DB    string `json:"db"`    // target database name
	Block string `json:"block"` // target block name
	Alias string `json:"alias"` // name used in FIND ... SELECT <alias>.field (defaults to Block)
	FK    string `json:"fk"`    // conventional foreign-key field on the source doc, e.g. "director_id"
}

// RelationDef is the full set of targets registered for one source block.
type RelationDef struct {
	SourceDB    string           `json:"source_db"`
	SourceBlock string           `json:"source_block"`
	Targets     []RelationTarget `json:"targets"`
}

// RelationManager persists and caches RELATE definitions. Definitions are
// stored as one JSON file per source db+block under
// <dataRoot>/__system/relations/, so they survive restarts the same way
// block metadata does.
type RelationManager struct {
	mu       sync.RWMutex
	dataRoot string
	cache    map[string]*RelationDef // key: sourceDB + "\x00" + sourceBlock
}

func NewRelationManager(dataRoot string) *RelationManager {
	return &RelationManager{
		dataRoot: dataRoot,
		cache:    make(map[string]*RelationDef),
	}
}

func relationKey(db, block string) string { return db + "\x00" + block }

func (rm *RelationManager) filePath(db, block string) string {
	return filepath.Join(rm.dataRoot, "__system", "relations", db+"__"+block+".json")
}

// fkFieldFor derives the conventional foreign-key field name for a target
// block, e.g. "directors" -> "director_id", "genres" -> "genre_id",
// "customers" -> "customer_id". This is a best-effort heuristic (not a
// full English inflector), matching the "<block>_id" convention.
func fkFieldFor(targetBlock string) string {
	return singularize(targetBlock) + "_id"
}

func singularize(name string) string {
	lower := strings.ToLower(name)
	switch {
	case strings.HasSuffix(lower, "ies") && len(name) > 3:
		return name[:len(name)-3] + "y"
	case strings.HasSuffix(lower, "ses") && len(name) > 3:
		return name[:len(name)-2]
	case strings.HasSuffix(lower, "s") && len(name) > 1:
		return name[:len(name)-1]
	default:
		return name
	}
}

// parseTargetSpec splits a RELATE target ("customers" or "crm.customers")
// into its database and block parts, defaulting the database to the
// source block's own database when none is given.
func parseTargetSpec(spec, defaultDB string) (db, block string, err error) {
	spec = strings.TrimSpace(spec)
	if spec == "" {
		return "", "", fmt.Errorf("empty target block in RELATE")
	}
	if idx := strings.Index(spec, "."); idx > 0 && idx < len(spec)-1 {
		return spec[:idx], spec[idx+1:], nil
	}
	return defaultDB, spec, nil
}

// Relate registers (replacing any previous definition) the relation
// targets for a source block. Each entry in targetSpecs is either a bare
// block name (same database as the source) or "db.block" for a
// cross-database relation.
func (rm *RelationManager) Relate(sourceDB, sourceBlock string, targetSpecs []string) (*RelationDef, error) {
	if sourceDB == "" || sourceBlock == "" {
		return nil, fmt.Errorf("source database and block are required")
	}
	if len(targetSpecs) == 0 {
		return nil, fmt.Errorf("RELATE requires at least one target block (USE <block1>[,<block2>,...])")
	}

	def := &RelationDef{SourceDB: sourceDB, SourceBlock: sourceBlock}
	seenAlias := make(map[string]bool, len(targetSpecs))

	for _, spec := range targetSpecs {
		targetDB, targetBlock, err := parseTargetSpec(spec, sourceDB)
		if err != nil {
			return nil, err
		}

		alias := targetBlock
		if seenAlias[alias] {
			return nil, fmt.Errorf("duplicate relation target: %q (alias %q already used)", spec, alias)
		}
		seenAlias[alias] = true

		def.Targets = append(def.Targets, RelationTarget{
			DB:    targetDB,
			Block: targetBlock,
			Alias: alias,
			FK:    fkFieldFor(targetBlock),
		})
	}

	if err := rm.save(def); err != nil {
		return nil, err
	}

	rm.mu.Lock()
	rm.cache[relationKey(sourceDB, sourceBlock)] = def
	rm.mu.Unlock()

	return def, nil
}

// Get returns the relation definition registered for a source block, if
// any, loading it from disk on first access and caching it afterwards.
func (rm *RelationManager) Get(sourceDB, sourceBlock string) (*RelationDef, bool) {
	rm.mu.RLock()
	if def, ok := rm.cache[relationKey(sourceDB, sourceBlock)]; ok {
		rm.mu.RUnlock()
		return def, true
	}
	rm.mu.RUnlock()

	def, err := rm.load(sourceDB, sourceBlock)
	if err != nil || def == nil {
		return nil, false
	}

	rm.mu.Lock()
	rm.cache[relationKey(sourceDB, sourceBlock)] = def
	rm.mu.Unlock()
	return def, true
}

func (rm *RelationManager) save(def *RelationDef) error {
	dir := filepath.Join(rm.dataRoot, "__system", "relations")
	if err := os.MkdirAll(dir, 0750); err != nil {
		return err
	}
	data, err := json.MarshalIndent(def, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(rm.filePath(def.SourceDB, def.SourceBlock), data, 0644)
}

func (rm *RelationManager) load(db, block string) (*RelationDef, error) {
	data, err := os.ReadFile(rm.filePath(db, block))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var def RelationDef
	if err := json.Unmarshal(data, &def); err != nil {
		return nil, err
	}
	return &def, nil
}

// Relate validates the target blocks exist and registers the relation
// definition for dbName.block via the engine's RelationManager.
func (e *Engine) Relate(dbName, block string, targetSpecs []string) (*RelationDef, error) {
	if !e.dirMgr.BlockExists(dbName, block) {
		return nil, ErrBlockNotFound
	}

	for _, spec := range targetSpecs {
		targetDB, targetBlock, err := parseTargetSpec(spec, dbName)
		if err != nil {
			return nil, err
		}
		if !e.dirMgr.BlockExists(targetDB, targetBlock) {
			return nil, fmt.Errorf("related block not found: %s.%s", targetDB, targetBlock)
		}
	}

	return e.relMgr.Relate(dbName, block, targetSpecs)
}
